title: Streamdata Gallery
url: aws-ec2-container-registry-service.api.streamdata.gallery
tag: AWS EC2 Container Registry Service
markdown: kramdown
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md", ".DS_Store"]
github_user: streamdata-gallery-organizations
github_repo: aws-ec2-container-registry-service
github_branch: master
collections:
  listings:
    output: true
    permalink: /listings/:path/
defaults:
  - scope:
      type: listings
    values:
      layout: listings
